name: 'fundment_analytics'
version: '1.0.0'
config-version: 2

profile: 'fundment'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  fundment_analytics:
    staging:
      +schema: staging
      # stg_fees overrides to incremental via stg_fees.yml
      +materialized: table
    reporting:
      +schema: reporting
      +materialized: table

vars:
  # LTV calculation windows in months
  ltv_windows: [1, 3, 6]
